import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// In the layout.tsx file, we have added NavBar and Footer around the {children} prop, and hence these components will be present in all our pages/sub pages. Nav bar will be present before the MainPageContent, and Footer will be present below the MainPage component.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>NavBar</h1>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  );
}
